---
title: "Evan L. Ray"
---

## About

I am an assistant professor of statistics in the [department of mathematics and statistics](https://www.mtholyoke.edu/acad/math) at [Mount Holyoke College](https://www.mtholyoke.edu).  I completed my PhD in statistics at the University of Massachusetts, Amherst.  In various research projects, I have developed methods to classify physical activity using accelerometer data and developed semi-parametric and ensemble models for predicting the timing and severity of the spread of infectious disease.  I work closely with the [Reich Lab](http://reichlab.io/) in the Department of Biostatistics and Epidemiology at the University of Massachusetts, Amherst.

Here is my CV: [pdf](Evan_L_Ray_CV.pdf)

## Teaching

### Current

[Stat 343: Mathematical Statistics](http://www.evanlray.com/stat343_s2020/)

[Stat 344ne: Introduction to Neural Networks](http://www.evanlray.com/stat344ne_s2020/)


### Previous

#### Fall 2019

Stat 242: Intermediate Statistics

Stat 340: Topics in Applied Regression

#### Spring 2019

Stat 242: Intermediate Statistics

Stat 343: Mathematical Statistics

#### Fall 2018

Stat 140: Introduction to the Ideas and Applications of Statistics

Stat 340: Applied Regression

#### Spring 2018

Stat 140: Introduction to the Ideas and Applications of Statistics

Stat 343: Mathematical Statistics

#### Fall 2017

Stat 140: Introduction to the Ideas and Applications of Statistics

## Contact

Evan L. Ray  
404C Clapp Laboratory  
Mount Holyoke College  
50 College St.  
South Hadley, MA 01075

eray@mtholyoke.edu