---
title: "Letters of Recommendation"
---

If I have agreed to write a recommendation for you, please provide me with as much of the following as possible:

 * an unofficial copy of your transcript,
 * a copy of your personal statement (if applicable), and
 * all necessary forms

Furthermore, at least two weeks before the first letter is due, please e-mail me your answers to the following questions (the more details the better):

1. What is your name, year, and major?
2. What are your preferred pronouns?
3. For what are you applying? (scholarship, graduate school, etc.)
4. List the programs to which you are applying, together with due dates.
5. How long have I known you (years/months), and what is my relationship(s) to you (instructor, advisor, etc.)? Have you graded or tutored for me? If so, for what class(es) and when?
6. For what class(es) have I had you, what final grade(s) did I assign you, and how did you distinguish yourself in my class(es)?
7. How would you describe yourself?
8. What are some of your academic accomplishments?
9. What are some of your nonacademic accomplishments?
10. What makes me particularly qualified to write a letter for you?
11. What makes you particularly qualified for this position/honor/award?
12. What are your long term goals and will this position/honor/award help? If so, how?
13. Additional comments (REU’s, summer research, interesting jobs, hobbies, etc.)?

Please also send me e-mail reminders as deadlines approach.  You don't need to write anything in the body of the email; the subject can just be "Reminder: recommendation letter due \_\_\_\_\_", filling in the blank with the due date(s).

Good luck!

(Note: This page is adapted/stolen from Jo Hardin at Pomona College.)
